services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: globetrottr-db
    environment:
      TZ: Europe/Warsaw
      POSTGRES_DB: globetrottr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./globetrottr_backend
      dockerfile: Dockerfile
    container_name: globetrottr-backend
    ports:
      - "8080:8080"
    environment:
      TZ: Europe/Warsaw
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/globetrottr
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM: ${MAIL_FROM}
    depends_on:
      postgres:
        condition: service_healthy
