CREATE TABLE user_fog
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  UUID,
    fog_area GEOMETRY(Geometry, 4326),
    CONSTRAINT pk_user_fog PRIMARY KEY (id)
);

CREATE TABLE users
(
    user_id            UUID         NOT NULL,
    username           VARCHAR(50)  NOT NULL,
    email              VARCHAR(100) NOT NULL,
    password_hash      VARCHAR(255),
    total_points       INTEGER,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    is_email_verified  BOOLEAN,
    is_enabled         BOOLEAN,
    account_non_locked BOOLEAN,
    role               VARCHAR(255) NOT NULL,
    auth_provider      VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE verification_codes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(6),
    user_id     UUID                                    NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_verification_codes PRIMARY KEY (id)
);

ALTER TABLE user_fog
    ADD CONSTRAINT uc_user_fog_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE verification_codes
    ADD CONSTRAINT uc_verification_codes_user UNIQUE (user_id);

ALTER TABLE user_fog
    ADD CONSTRAINT FK_USER_FOG_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE verification_codes
    ADD CONSTRAINT FK_VERIFICATION_CODES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);