CREATE TABLE user_details
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    UUID                                    NOT NULL,
    avatar_url VARCHAR(500),
    bio        VARCHAR(255),
    CONSTRAINT pk_user_details PRIMARY KEY (id)
);

ALTER TABLE user_details
    ADD CONSTRAINT uc_user_details_user UNIQUE (user_id);

ALTER TABLE user_details
    ADD CONSTRAINT FK_USER_DETAILS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);
