CREATE TABLE regions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    type           VARCHAR(255)                            NOT NULL,
    geom           GEOMETRY(MultiPolygon, 4326)            NOT NULL,
    total_area_km2 DOUBLE PRECISION,
    CONSTRAINT pk_regions PRIMARY KEY (id)
);

ALTER TABLE regions
    ADD CONSTRAINT uc_regions_name UNIQUE (name);

CREATE INDEX idx_regions_geom ON regions USING GIST (geom);