CREATE TABLE user_region_statistics
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id              UUID                                    NOT NULL,
    region_id            BIGINT                                  NOT NULL,
    discovered_area_km2  DOUBLE PRECISION,
    discovery_percentage DOUBLE PRECISION,
    CONSTRAINT pk_user_region_statistics PRIMARY KEY (id)
);

CREATE TABLE user_statistics
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                 UUID                                    NOT NULL,
    total_discovered_km2    DOUBLE PRECISION,
    visited_countries_count INTEGER,
    completed_quests_count  INTEGER,
    current_streak          INTEGER,
    last_activity_date      date,
    last_updated            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_statistics PRIMARY KEY (id)
);

ALTER TABLE user_region_statistics
    ADD CONSTRAINT uc_user_region_statistics_user_id_region_id UNIQUE (user_id, region_id);

ALTER TABLE user_statistics
    ADD CONSTRAINT uc_user_statistics_user UNIQUE (user_id);

ALTER TABLE user_region_statistics
    ADD CONSTRAINT FK_USER_REGION_STATISTICS_ON_REGION FOREIGN KEY (region_id) REFERENCES regions (id);

ALTER TABLE user_region_statistics
    ADD CONSTRAINT FK_USER_REGION_STATISTICS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_statistics
    ADD CONSTRAINT FK_USER_STATISTICS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);