include: package:very_good_analysis/analysis_options.yaml

plugins:
  riverpod_lint: ^3.1.4

analyzer:
  language:
    strict-casts: false
  
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

# turn off a rule if it's annoying
linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: true
    prefer_int_literals: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: false
    sort_constructors_first: false
    directives_ordering: false
    avoid_positional_boolean_parameters: false
    curly_braces_in_flow_control_structures: false
    omit_local_variable_types: false
    cascade_invocations: false
    avoid_print: false